name: Stern Inbound Marketing
favicon: null
layout_spectrum: 0.64144
typography_spectrum: 0.3989125150255859
title: Stern A Leading Creative Inbound Marketing Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-26050282-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8fbae1'
    - '#e3e2e8'
    - '#4e8fc2'
    - '#803904'
    - '#3e5a7d'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
