name: Stern Inbound Marketing
favicon: null
layout_spectrum: 0.20047121308743954
typography_spectrum: 0.3989125150255859
title: Stern A Leading Creative Inbound Marketing Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-26050282-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.347879521548748
  lightness: 0.7374186355154961
  saturation: 0.8173164732288569
  rhythmicContrast: 0.8476173740345985
purpose: []
